INSERT INTO blogful_articles (title, content, date_published)
VALUES
    ('Aliens are rea;?!', 'Yulp, aliens are definitly real man.', now() - '21 days'::INTERVAL),
    ('The crazies think aliens are real!', 'Crazy people think aliens are real', now() - '21 days'::INTERVAL),
    ('Am I done writing real article names?!', 'Yes I am definitly done writing silly articles information.', now() - '21 days'::INTERVAL),
    ('Article 4', 'Content for article 4.', now() - '21 days'::INTERVAL),
    ('Article 5', 'Content for article 5.', now() - '21 days'::INTERVAL),
    ('Article 6', 'Content for article 6.', now() - '21 days'::INTERVAL),
    ('Article 7', 'Content for article 7.', now() - '21 days'::INTERVAL),
    ('Article 8', 'Content for article 8.', now() - '21 days'::INTERVAL),
    ('Article 9', 'Content for article 9.', now() - '21 days'::INTERVAL),
    ('Article 10', 'Content for article 10.', now() - '21 days'::INTERVAL),
    ('Article 11', 'Content for article 11.', now() - '21 days'::INTERVAL),
    ('Article 12', 'Content for article 12.', now() - '21 days'::INTERVAL),
    ('Article 13', 'Content for article 13.', now() - '21 days'::INTERVAL),
    ('Article 14', 'Content for article 14.', now() - '21 days'::INTERVAL),
    ('Article 15', 'Content for article 15.', now() - '21 days'::INTERVAL),
    ('Article 16', 'Content for article 16.', now() - '21 days'::INTERVAL),
    ('Article 17', 'Content for article 17.', now() - '21 days'::INTERVAL),
    ('Article 18', 'Content for article 18.', now() - '21 days'::INTERVAL),
    ('Article 19', 'Content for article 19.', now() - '21 days'::INTERVAL),
    ('Article 20', 'Content for article 20.', now() - '21 days'::INTERVAL),
    ('Article 21', 'Content for article 21.', now() - '21 days'::INTERVAL),
    ('Article 22', 'Content for article 22.', now() - '21 days'::INTERVAL),
    ('Article 23', 'Content for article 23.', now() - '21 days'::INTERVAL),
    ('Article 24', 'Content for article 24.', now() - '21 days'::INTERVAL),
    ('Article 25', 'Content for article 25.', now() - '21 days'::INTERVAL),
    ('Article 26', 'Content for article 26.', now() - '21 days'::INTERVAL),
    ('Article 27', 'Content for article 27.', now() - '21 days'::INTERVAL),
    ('Article 28', 'Content for article 28.', now() - '21 days'::INTERVAL),
    ('Article 29', 'Content for article 29.', now() - '21 days'::INTERVAL),
    ('Article 30', 'Content for article 30.', now() - '21 days'::INTERVAL);